# Generated by Django 2.1.3 on 2018-11-28 16:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Mascota',
            fields=[
                ('codigoMascota', models.AutoField(primary_key=True, serialize=False)),
                ('fotoMascota', models.ImageField(upload_to='fotos/')),
                ('nombreMascota', models.CharField(max_length=20, verbose_name='Nombre Mascota')),
                ('razaMascota', models.CharField(default='', max_length=30, verbose_name='Raza Mascota')),
                ('descripcionMascota', models.CharField(default='', max_length=50, verbose_name='Descripcion')),
                ('estado', models.CharField(max_length=20, verbose_name='Estado')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contacto', models.CharField(default='', max_length=12)),
                ('region', models.CharField(default='Metropolitana', max_length=20)),
                ('vivienda', models.CharField(default='', max_length=20)),
                ('perfil', models.CharField(default='Adoptante', max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
