# Generated by Django 2.1.2 on 2018-11-09 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Back', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='region',
            field=models.CharField(default='Metropolitana', max_length=20),
        ),
        migrations.AlterField(
            model_name='mascota',
            name='codigoMascota',
            field=models.AutoField(default='', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='mascota',
            name='estado',
            field=models.CharField(default='Rescatado', max_length=20),
        ),
        migrations.AlterField(
            model_name='mascota',
            name='nombreMascota',
            field=models.CharField(default='', max_length=20),
        ),
    ]
