# Generated by Django 2.1.2 on 2018-11-09 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Back', '0003_usuario_vivienda'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='contacto',
            field=models.CharField(default='', max_length=12),
        ),
    ]
