# Generated by Django 2.1.2 on 2018-11-09 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Back', '0004_usuario_contacto'),
    ]

    operations = [
        migrations.AddField(
            model_name='mascota',
            name='fotoMascota',
            field=models.ImageField(default=1, upload_to='fotos/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mascota',
            name='codigoMascota',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='mascota',
            name='descripcionMascota',
            field=models.CharField(default='', max_length=50, verbose_name='Descripcion'),
        ),
        migrations.AlterField(
            model_name='mascota',
            name='estado',
            field=models.CharField(max_length=20, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='mascota',
            name='nombreMascota',
            field=models.CharField(max_length=20, verbose_name='Nombre Mascota'),
        ),
        migrations.AlterField(
            model_name='mascota',
            name='razaMascota',
            field=models.CharField(default='', max_length=30, verbose_name='Raza Mascota'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='perfil',
            field=models.CharField(default='Usuario', max_length=20),
        ),
    ]
