# Generated by Django 2.1.2 on 2018-11-10 00:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Back', '0005_auto_20181109_2010'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuario',
            options={},
        ),
    ]
