# Generated by Django 2.1.2 on 2018-11-10 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Back', '0006_auto_20181109_2127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='perfil',
            field=models.CharField(default='Adoptante', max_length=20),
        ),
    ]
